# homelab-talos/clusters/kalecgos/talconfig.yaml
clusterName: bleu-kalecgos
talosVersion: v1.13.4
kubernetesVersion: v1.36.2

endpoint: https://192.168.1.11:6443

# Désactiver le CNI par défaut (Flannel) + kube-proxy : Cilium prend le relais
cniConfig:
  name: none

nodes:
  - hostname: vert-eranikus
    ipAddress: 192.168.1.11
    controlPlane: true
    installDiskSelector:
      serial: "202512100355"   # nvme0n1 = OS

# Patches cluster-wide
patches:
  - |-
    cluster:
      allowSchedulingOnControlPlanes: true
  - |-
    cluster:
      proxy:
        disabled: true 